version: '3'
services:
    grafana:
        container_name: monitoring-grafana
        image: grafana/grafana:latest
        hostname: grafana
        restart: unless-stopped
        user: '0'
        networks:
            - internal
        ports:
            - '3000:3000'
        env_file:
            - ./grafana/.env
            - ./influxdb/.env
        volumes:
            - ./grafana/data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
            - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
            - ./grafana/datasources:/etc/grafana/provisioning/datasources
        depends_on:
            - influxdb

    influxdb:
        container_name: monitoring-influxdb
        image: influxdb:latest
        hostname: influxdb
        restart: unless-stopped
        networks:
            - internal
        ports:
            - '8086:8086'
        volumes:
            - ./influxdb/data:/var/lib/influxdb2
            - ./influxdb/config:/etc/influxdb2
        env_file:
            - ./influxdb/.env
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup

    telegraf:
        image: telegraf
        depends_on:
            - influxdb
        container_name: telegraf
        restart: always
        user: '${DOCKER_USER}'
        networks:
            - internal
        env_file:
            - ./influxdb/.env
        links:
            - influxdb:influxdb
        tty: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
networks:
    internal:
        driver: bridge

volumes:
    grafana_data:
    influxdb_data:
    telegraf_data:
